#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: testaccount
  CLOUD_SQL_PASSWORD: 123456
  CLOUD_SQL_DATABASE_NAME: seller
  CLOUD_SQL_CONNECTION_NAME: turnkey-channel-402720:us-east1:seller-6156
